{% set name = "jaraco.test" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaraco_test-{{ version }}.tar.gz
  sha256: 4c04616455c43a281947da3177099e3246849117e3057c49bc9644c28ba7d375

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >=3.8
    - jaraco.functools
    - jaraco.context
    - jaraco.collections

test:
  imports:
    - jaraco.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jaraco/jaraco.test
  summary: Testing support by jaraco
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
